---
# This playbook deploys the whole application stack in this site.  

# Apply common configuration to all hosts
- hosts: all
  roles:
  - common

- hosts: controller
  roles:
  - mysql
  - rabbitmq
  - keystone
  - keystone_db_init
