---
# This role will install MySQL and create db user and give permissions.

- name: Install Mysql package
  yum: name={{ item }} state=present
  with_items:
   - mysql
   - mysql-server
   - MySQL-python

- name: Create Mysql configuration file
  copy: src=etc/my.cnf dest=/etc/my.cnf

- name: Start Mysql Service
  service: name=mysqld state=started enabled=true

#- name: Config Mysql Root User
#  mysql_user: name=root  password={{ db_root_password }} priv=*.*:ALL state=present
