---
# This role will install and config keystone

- name: Create Keystone DB
  mysql_db: name=keystone state=present

- name: Create Keystone DB User 
  mysql_user: host={{ item }} name=keystone  password={{ keystone_mysql_password }} priv=keystone.*:ALL state=present
  with_items:
    - "{{ management_network }}"
    - localhost
- name: Install python-sqlalchemy because icehouse repo has bug now...
  yum: name=https://repos.fedorapeople.org/repos/openstack/openstack-juno/epel-7/python-sqlalchemy-0.9.7-2.el7.centos.x86_64.rpm state=present

- name: Install keystone and keystone client package
  yum: name={{ item }} state=present
  with_items:
   - openstack-keystone
   - python-keystoneclient
  
